/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranslationRouteImport } from './routes/translation'
import { Route as TechnicalProposalRouteImport } from './routes/technical-proposal'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as OthersRouteImport } from './routes/others'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegulatoryIndexRouteImport } from './routes/regulatory.index'
import { Route as RegulatorySlugRouteImport } from './routes/regulatory.$slug'
import { Route as ExploreSlugRouteImport } from './routes/explore.$slug'
import { Route as CertificateIdRouteImport } from './routes/certificate.$id'

const TranslationRoute = TranslationRouteImport.update({
  id: '/translation',
  path: '/translation',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalProposalRoute = TechnicalProposalRouteImport.update({
  id: '/technical-proposal',
  path: '/technical-proposal',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const OthersRoute = OthersRouteImport.update({
  id: '/others',
  path: '/others',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatoryIndexRoute = RegulatoryIndexRouteImport.update({
  id: '/regulatory/',
  path: '/regulatory/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatorySlugRoute = RegulatorySlugRouteImport.update({
  id: '/regulatory/$slug',
  path: '/regulatory/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreSlugRoute = ExploreSlugRouteImport.update({
  id: '/explore/$slug',
  path: '/explore/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateIdRoute = CertificateIdRouteImport.update({
  id: '/certificate/$id',
  path: '/certificate/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/career': typeof CareerRoute
  '/certificates': typeof CertificatesRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/others': typeof OthersRoute
  '/projects': typeof ProjectsRoute
  '/security': typeof SecurityRoute
  '/technical-proposal': typeof TechnicalProposalRoute
  '/translation': typeof TranslationRoute
  '/certificate/$id': typeof CertificateIdRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/regulatory/$slug': typeof RegulatorySlugRoute
  '/regulatory/': typeof RegulatoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/career': typeof CareerRoute
  '/certificates': typeof CertificatesRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/others': typeof OthersRoute
  '/projects': typeof ProjectsRoute
  '/security': typeof SecurityRoute
  '/technical-proposal': typeof TechnicalProposalRoute
  '/translation': typeof TranslationRoute
  '/certificate/$id': typeof CertificateIdRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/regulatory/$slug': typeof RegulatorySlugRoute
  '/regulatory': typeof RegulatoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/career': typeof CareerRoute
  '/certificates': typeof CertificatesRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/others': typeof OthersRoute
  '/projects': typeof ProjectsRoute
  '/security': typeof SecurityRoute
  '/technical-proposal': typeof TechnicalProposalRoute
  '/translation': typeof TranslationRoute
  '/certificate/$id': typeof CertificateIdRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/regulatory/$slug': typeof RegulatorySlugRoute
  '/regulatory/': typeof RegulatoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/career'
    | '/certificates'
    | '/clients'
    | '/contact'
    | '/gallery'
    | '/others'
    | '/projects'
    | '/security'
    | '/technical-proposal'
    | '/translation'
    | '/certificate/$id'
    | '/explore/$slug'
    | '/regulatory/$slug'
    | '/regulatory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/career'
    | '/certificates'
    | '/clients'
    | '/contact'
    | '/gallery'
    | '/others'
    | '/projects'
    | '/security'
    | '/technical-proposal'
    | '/translation'
    | '/certificate/$id'
    | '/explore/$slug'
    | '/regulatory/$slug'
    | '/regulatory'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/career'
    | '/certificates'
    | '/clients'
    | '/contact'
    | '/gallery'
    | '/others'
    | '/projects'
    | '/security'
    | '/technical-proposal'
    | '/translation'
    | '/certificate/$id'
    | '/explore/$slug'
    | '/regulatory/$slug'
    | '/regulatory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CareerRoute: typeof CareerRoute
  CertificatesRoute: typeof CertificatesRoute
  ClientsRoute: typeof ClientsRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  OthersRoute: typeof OthersRoute
  ProjectsRoute: typeof ProjectsRoute
  SecurityRoute: typeof SecurityRoute
  TechnicalProposalRoute: typeof TechnicalProposalRoute
  TranslationRoute: typeof TranslationRoute
  CertificateIdRoute: typeof CertificateIdRoute
  ExploreSlugRoute: typeof ExploreSlugRoute
  RegulatorySlugRoute: typeof RegulatorySlugRoute
  RegulatoryIndexRoute: typeof RegulatoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/translation': {
      id: '/translation'
      path: '/translation'
      fullPath: '/translation'
      preLoaderRoute: typeof TranslationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-proposal': {
      id: '/technical-proposal'
      path: '/technical-proposal'
      fullPath: '/technical-proposal'
      preLoaderRoute: typeof TechnicalProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/others': {
      id: '/others'
      path: '/others'
      fullPath: '/others'
      preLoaderRoute: typeof OthersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulatory/': {
      id: '/regulatory/'
      path: '/regulatory'
      fullPath: '/regulatory/'
      preLoaderRoute: typeof RegulatoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulatory/$slug': {
      id: '/regulatory/$slug'
      path: '/regulatory/$slug'
      fullPath: '/regulatory/$slug'
      preLoaderRoute: typeof RegulatorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$slug': {
      id: '/explore/$slug'
      path: '/explore/$slug'
      fullPath: '/explore/$slug'
      preLoaderRoute: typeof ExploreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$id': {
      id: '/certificate/$id'
      path: '/certificate/$id'
      fullPath: '/certificate/$id'
      preLoaderRoute: typeof CertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CareerRoute: CareerRoute,
  CertificatesRoute: CertificatesRoute,
  ClientsRoute: ClientsRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  OthersRoute: OthersRoute,
  ProjectsRoute: ProjectsRoute,
  SecurityRoute: SecurityRoute,
  TechnicalProposalRoute: TechnicalProposalRoute,
  TranslationRoute: TranslationRoute,
  CertificateIdRoute: CertificateIdRoute,
  ExploreSlugRoute: ExploreSlugRoute,
  RegulatorySlugRoute: RegulatorySlugRoute,
  RegulatoryIndexRoute: RegulatoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
